import { writeFileSync } from "fs"

const releases = [
  {
    id: "1",
    slug: "ep-the-love",
    title: "EP. The Love",
    type: "EP",
    releaseDate: "2024-02-14",
    coverArt: "/images/releases/ep-the-love.jpg",
    description: "A heartfelt EP exploring love in all its forms.",
    streamingLinks: {
      spotify: "#",
      youtube: "#",
      apple: "#",
      amazon_music: "#",
      youtube_music: "#",
      soundcloud: "#",
      tidal: "#",
      deezer: "#",
    },
    featured: true,
    status: "published",
    createdAt: "2024-02-14T00:00:00.000Z",
    updatedAt: "2024-02-14T00:00:00.000Z",
  },
  {
    id: "2",
    slug: "cant-stop",
    title: "Can't Stop",
    type: "Single",
    releaseDate: "2024-05-01",
    coverArt: "/images/releases/cant-stop.jpg",
    description: "Can't Stop is a high-energy track about relentless drive.",
    streamingLinks: {
      spotify: "#",
      youtube: "#",
      apple: "#",
      amazon_music: "#",
      youtube_music: "#",
      soundcloud: "#",
      tidal: "#",
      deezer: "#",
    },
    featured: true,
    status: "published",
    createdAt: "2024-05-01T00:00:00.000Z",
    updatedAt: "2024-05-01T00:00:00.000Z",
  },
  {
    id: "3",
    slug: "not-me",
    title: "Not Me",
    type: "Single",
    releaseDate: "2023-11-10",
    coverArt: "/images/releases/not-me.jpg",
    description: "A moody introspective single.",
    streamingLinks: {
      spotify: "#",
      youtube: "#",
      apple: "#",
      soundcloud: "#",
    },
    featured: false,
    status: "published",
    createdAt: "2023-11-10T00:00:00.000Z",
    updatedAt: "2023-11-10T00:00:00.000Z",
  },
  {
    id: "4",
    slug: "like-me",
    title: "Like Me",
    type: "Single",
    releaseDate: "2023-07-20",
    coverArt: "/images/releases/like-me.jpg",
    streamingLinks: {
      spotify: "#",
      youtube: "#",
      apple: "#",
      soundcloud: "#",
    },
    featured: false,
    status: "published",
    createdAt: "2023-07-20T00:00:00.000Z",
    updatedAt: "2023-07-20T00:00:00.000Z",
  },
  {
    id: "5",
    slug: "lets-get-drunk",
    title: "Let's Get Drunk",
    type: "Single",
    releaseDate: "2023-03-15",
    coverArt: "/images/releases/lets-get-drunk.jpg",
    streamingLinks: {
      spotify: "#",
      youtube: "#",
      apple: "#",
      soundcloud: "#",
    },
    featured: false,
    status: "published",
    createdAt: "2023-03-15T00:00:00.000Z",
    updatedAt: "2023-03-15T00:00:00.000Z",
  },
]

writeFileSync("db/music.json", JSON.stringify(releases, null, 2))
console.log(`✅ Seeded ${releases.length} releases into db/music.json`)
